name: Cherokee-TTS-rlfss
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.13.0
  - aiohttp=3.7.4.post0
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.2
  - certifi=2021.10.8
  - chardet=4.0.0
  - click=8.0.1
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - coverage=5.5
  - cryptography=3.4.8
  - cudatoolkit=11.1.74
  - cython=0.29.24
  - dataclasses=0.8
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.36.1
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libprotobuf=3.17.2
  - libstdcxx-ng=9.3.0
  - libuv=1.40.0
  - markdown=3.3.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - multidict=5.1.0
  - ncurses=6.2
  - ninja=1.10.2
  - oauthlib=3.1.1
  - openssl=1.1.1l
  - pip=21.2.4
  - protobuf=3.17.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycosat=0.6.3
  - pycparser=2.20
  - pydub=0.25.1
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.9.7
  - python_abi=3.9
  - pytorch=1.9.1
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - ruamel_yaml=0.15.100
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.11
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - werkzeug=2.0.1
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.6.0
  - zlib=1.2.11
  - pip:
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - audioread==2.1.9
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - decorator==5.1.0
    - future==0.18.2
    - hydra-core==1.1.1
    - idna==3.3
    - importlib-resources==5.2.2
    - joblib==1.1.0
    - librosa==0.8.1
    - llvmlite==0.37.0
    - numba==0.54.1
    - numpy==1.20.3
    - omegaconf==2.1.1
    - packaging==21.0
    - pooch==1.5.2
    - pyloudnorm==0.1.0
    - pyparsing==2.4.7
    - pyyaml==6.0
    - resampy==0.2.2
    - scikit-learn==1.0
    - scipy==1.7.1
    - soundfile==0.10.3.post1
    - tacotron==0.1.1
    - threadpoolctl==3.0.0
    - toml==0.10.2
    - tqdm==4.62.3
    - univoc==0.2.1
    - urllib3==1.26.7
